import logo from './logo.png';
import logo_1 from './Logo-1.png';
import bg_texture from './background-texture.png';
import property1 from './property-1.png';
import usersIcon from './users_icon.png';
import factory from './Fac 1.png';
import chairman from './chairman.png';
import group1 from './Group 26.png';
import group2 from './Group 26 (1).png';
import qualityPolicy from './files/Quality-Policy.pdf';
export { logo, logo_1, bg_texture, property1, usersIcon, factory, chairman, group1, group2 ,qualityPolicy };
